### ISSUE TITLE
为本仓库添加 Git 分支的提议

### ISSUE THREAD

**Issue by muziing** [icexmoon/PEP-CN#4]
我注意到本仓库暂时只有一个 `main` 分支，但所有提交直接合并至 `main` 可能引起错误和 Git 记录混乱。

建议增加一个 `dev` 分支。任何译者在提交新的译文时首先提交至 `dev` 分支，经他人一定的检查后再决定：

- 有一定翻译/排版/版权声明错误，撤销该次 Git 操作，更正错误后再次提交
- 译文质量良好，可以 merge 到 `main` 分支

**Comment by icexmoon** [comment]
好的，我研究一下后会添加的。
感谢对本项目的建议和贡献。

**Comment by icexmoon** [comment]
dev 分支已建立。
